# Generated by Django 6.0.7 on 2026-07-18 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedModelRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('global_accuracy', models.FloatField(blank=True, null=True)),
                ('global_precision', models.FloatField(blank=True, null=True)),
                ('global_recall', models.FloatField(blank=True, null=True)),
                ('global_f1', models.FloatField(blank=True, null=True)),
                ('global_auc', models.FloatField(blank=True, null=True)),
                ('communication_bytes', models.BigIntegerField(default=0)),
                ('num_clients', models.IntegerField()),
                ('num_clients_available', models.IntegerField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=100)),
                ('model_checkpoint', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'federated_model_rounds',
            },
        ),
        migrations.CreateModel(
            name='MilitaryBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.CharField(max_length=100, unique=True)),
                ('base_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('ip_subnet', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'military_bases',
            },
        ),
        migrations.CreateModel(
            name='ClientMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_accuracy', models.FloatField()),
                ('local_precision', models.FloatField()),
                ('local_recall', models.FloatField()),
                ('local_f1', models.FloatField()),
                ('local_auc', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField()),
                ('anomaly_samples', models.IntegerField(blank=True, null=True)),
                ('benign_samples', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('upload_time_ms', models.FloatField()),
                ('download_time_ms', models.FloatField(blank=True, null=True)),
                ('local_training_time_sec', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.federatedmodelround')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.militarybase')),
            ],
            options={
                'db_table': 'client_metrics',
                'unique_together': {('round', 'base')},
            },
        ),
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField()),
                ('dest_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField()),
                ('dest_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=20)),
                ('packet_size', models.IntegerField()),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('packets_sent', models.IntegerField(default=0)),
                ('packets_received', models.IntegerField(default=0)),
                ('payload_entropy', models.FloatField()),
                ('inter_arrival_time', models.FloatField()),
                ('syn_count', models.IntegerField(default=0)),
                ('ack_count', models.IntegerField(default=0)),
                ('fin_count', models.IntegerField(default=0)),
                ('rst_count', models.IntegerField(default=0)),
                ('duration', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(default='benign', max_length=20)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.militarybase')),
            ],
            options={
                'db_table': 'network_traffic',
                'indexes': [models.Index(fields=['base', 'timestamp'], name='network_tra_base_id_a7b978_idx'), models.Index(fields=['src_ip', 'timestamp'], name='network_tra_src_ip_d837fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreatDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('dest_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dest_port', models.IntegerField(blank=True, null=True)),
                ('threat_type', models.CharField(choices=[('dos', 'DoS/DDoS'), ('port_scan', 'Port Scanning'), ('brute_force', 'Brute Force'), ('malware', 'Malware Traffic'), ('data_exfil', 'Data Exfiltration'), ('unknown', 'Unknown')], max_length=50)),
                ('confidence_score', models.FloatField()),
                ('anomaly_score', models.FloatField()),
                ('key_features', models.JSONField()),
                ('threat_indicators', models.JSONField(blank=True, null=True)),
                ('is_isolated', models.BooleanField(default=False)),
                ('isolation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.militarybase')),
            ],
            options={
                'db_table': 'threat_detections',
                'indexes': [models.Index(fields=['base', 'detected_at'], name='threat_dete_base_id_0827f1_idx'), models.Index(fields=['confidence_score'], name='threat_dete_confide_3d960d_idx')],
            },
        ),
    ]
