# Generated by Django 6.0.7 on 2026-07-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federatedmodelround',
            name='centralized_equivalent_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
