# Generated by Django 6.0.7 on 2026-07-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_federatedmodelround_centralized_equivalent_bytes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threatdetection',
            options={'ordering': ['-detected_at']},
        ),
    ]
